### ISSUE TITLE
Events amplitudes are not showing anymore in Sefran

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#118]
Greetings all,

We noticed a bug which appeared after the commit number ea64753ead015babe5d17238655d3c20696383cc (for eent amplitude keyboard shortcuts).
Events amplitudes are not displayed anymore when we look at the sefran. 

We investigated and found that the "xx_" prefix added to the $amplitudes variables is implicated. In some parts of the code, this prefix is being removed but not everywhere, which causes some variables not to find the right value (exemple in "sub mcinfo" definition).

Thanks in advance for your help :)

**Comment by beaudu** [comment]
The prefix was added only to sort the amplitudes list because hash keys in Perl are randomly sorted.
