### ISSUE TITLE
XML2 module import issue

### ISSUE THREAD

**Issue by PierreS-alpha** [IPGP/webobs#120]
Hi,

I did an update of my dev WebObs and I face the following error when I want to see my Grid:

`Can't locate WebObs/XML2.pm in @INC (you may need to install the WebObs::XML2 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/local/share/perl/5.34.0/WebObs/Mapping.pm line 46. BEGIN failed--compilation aborted at /usr/local/share/perl/5.34.0/WebObs/Mapping.pm line 46. Compilation failed in require at /opt/webobs/CODE/cgi-bin/showGRID.pl line 38. BEGIN failed--compilation aborted
`

The problem comes from this import, committed on Nov 14, 2022

https://github.com/IPGP/webobs/blob/16e466a0b22089347e3bc601483e46a0652eeb5d/CODE/cgi-bin/WebObs/Mapping.pm#L46

But this new module XML2 is not present in the Git repository. @beaudu are you sure you correctly committed this (I suppose) new XML2 module?

Thanks a lot,
Pierre

**Comment by beaudu** [comment]
Thanks Pierre. The forgotten module is committed. You might need to run the setup again (perl modules system-wide action).
