### ISSUE TITLE
csv export of GPS coordinates

### ISSUE THREAD

**Issue by PierreS-alpha** [IPGP/webobs#129]
Hi,

When you export the coordinates of a GPS station in CSV, and you want the complete range of data, you get only the last 300 values.

This is not the case with data exported in text format.

(Tested on OVPF's WebObs with the BORG station)

**Comment by beaudu** [comment]
Hi,
I am not sure to understand what is the context and what are the "coordinates of a GPS station". Can you specify which function/page/code is concerned (showGRID.pl, showNODE.pl, showOUTG.pl, ...), if this is about the node's coordinates or the data file from GNSS proc, or other... ?

**Comment by beaudu** [comment]
only TXT is exported in OUTG.
