### ISSUE TITLE
MC3 : cannot select hours for current day

### ISSUE THREAD

**Issue by beaudu** [IPGP/webobs#14]
When selecting hours other than default (00h to 23h) for the current day, no data come out. The problem does not appear for other days or if the first day is not today...

**Comment by XavierBeguin** [comment]
You mean, in the Main Courante produced by `mc3.pl`, selecting today's date as the start date and hours other than 00h to 23h would return no data ?

May be I am missing something, but I could not reproduce this issue. The events seem to be filtered as expected (On Webobs 2.1.2c and using Firefox 67.)

**Comment by beaudu** [comment]
as identified by @indrarudianto (see issue #86), the bug occured only for the last day of the month. That why @XavierBeguin was not able to reproduce it.
