### ISSUE TITLE
MC3 file corruption

### ISSUE THREAD

**Issue by JuNOVAR** [IPGP/webobs#141]
Hello,

The daybook (translation of "main courante") file of webobs can become corrupted, likely due to simultaneous write operations to the file. In Guadeloupe, we encounter this type of issue approximately once a year.

Here is an example of such a bug that occurred on 10/16 between 2:42 AM and 3:42 AM (local time).

The line:
643|2023-10-14|07:27:33.84|VOLCTECT|Faible|4.44|s|0|1||GL.LKG.00.HHZ|0|SEFRAN3_OVSG|://ovsg2023ufonjs|20231014072734.png|CBe/20231014T102033|template not detected

had become:
643|2023-10-14|07:27:33.84|VOLCTECT|Faible|4.44|s|0|1||GL.LKG.00.HHZ|0|SEFRAN3_OVSG|://ovsg2023ufonjs|20231014072734.png|CBe/20231014T102033|temBe/20231014T102033|template not detected

As a result, we are required to manually correct the daybook file.

Maybe we could integrate this data into the database to rectify the issue.

**Comment by beaudu** [comment]
Hi,
The "manual" edition of MC (through the sefran3 event form) is protected by lock file and timestamp. Can you verify that your file has been corrupted by 2 simultaneous manual editing (this is supposed to never happen...) or might be you have other local scripts that modify the MC file ?

**Comment by JuNOVAR** [comment]
The line from the previous example in the daybook was randomly modified during a file write.

There are several scripts that edit the daybook in webobs: fdsnws-event2mc3.pl, editMC3.pl, seiscomp2mc3, VolcAuto.pm...
These scripts use several different locking mechanisms. It would be better to use only one function to avoid issues.
I think our problem is attribuate to "VolcAuto.pm" that uses a different lock file name.

Moreover, the current locking system is not entirely reliable because, during nearly simultaneous events, it is possible that neither of the two concurrent scripts has locked the file yet, potentially resulting in two simultaneous writes. The risk is aggravated by the fact that the lock implementation is not optimal.
In race condition, it is necessary to use more robust tools such as the flock system call (as you already did).

However, I think it would be better to use a database, which would solve concurrency problems.

**Comment by beaudu** [comment]
thanks for the analysis and details.
VolcAuto.pm is a local development of your observatory that has been very recently pushed to the official repository, but not yet reviewed. Only OVSG is using it, since it needs specific and undocumented installation of other external tools. So I propose to close this issue.
The use of a local database instead of flat files is already planned: it needs some development and writing one-shot migration tools. You are perfectly right, this will solve this kind of problem (and others!).
