### ISSUE TITLE
sefran3 : fdsnws-dataselect stream with no data badly handled

### ISSUE THREAD

**Issue by jmsaurel** [IPGP/webobs#15]
When using fdsnws-dataselect archive source, the handling of a stream returning no data should be improved.
Here is the current situation
- if the fdsnws returns `204` for no data, wget hang up indefinitely
- if the fdsnws returns `404` for no data (option `nodata=404`), sefran3 throw an error because there is an empty mseed file.

Possible solution : 
- use curl instead of wget (curl doesn't hang up when http return code is `204`)
- if mseed file is empty, just spit an error message and continue

**Comment by beaudu** [comment]
ok, it seems that these problems have been solved in the fdsnws-dataselect for PROCS (readfmtdata_miniseed.m). We have to adapt the solution to sefran3, which do not use generic proc's data functions reading.
Possibly but harder work, modify sefran3 data reading part to use data reading like other procs do...

**Comment by jmsaurel** [comment]
we could simplify the code by using `POST` method instead of `GET`.
The loop on `sfr` writes the post file and a single `wget` command is used to retrieve all the channels.
I will try that.

Using readfmtdata would of course be nicer, but requires more work.

**Comment by jmsaurel** [comment]
Commit [d1e3b](https://github.com/IPGP/webobs/commit/d1e3b1abf8f9996df45cb399091c52806cc9ea50) uses `POST` method and should solve the issue and improve the efficiency

Now, only one request is made for each SefraN minute and it's much less likely that there is no data at all.
