### ISSUE TITLE
proc HYPOMAP: MSK filter issue with data format scevtlog

### ISSUE THREAD

**Issue by beaudu** [IPGP/webobs#17]
In HYPOMAP procs, defining `MSKLIM` key, i.e., filtering of an intensity range of quakes, together with `scevtlog` data format will result in excluding all data (because intensity is not defined in that format). For that reason, `MSKLIM` key has been commented by administrators in proc's configuration.
This abnormal behavior must be fixed in future version.

**Comment by jmsaurel** [comment]
This probably also concerns `fdsnws-event` format as intensity is only read from `hyp71sum2k` format
