### ISSUE TITLE
postboard bad handling of WEBOBS_ID special characters

### ISSUE THREAD

**Issue by jmsaurel** [IPGP/webobs#30]
The postboard doesn't handle correctly special character (at least `'`) in `WEBOBS_ID` variable.

When calling the mailer and building the subject string of the mail, all special characters in it should be escaped.

Or special characters should be forbidden in `WEBOBS_ID` variable during setup.

**Comment by beaudu** [comment]
This fix will replace by an underscore any invalid characters (other than alphanumeric and minus) in `WEBOBS_ID` string when using setup install script. Note that variable is still editable by user in `WEBOBS.rc`.
