### ISSUE TITLE
Bugfix of channel list in formNODE.pl

### ISSUE THREAD

**Issue by bossonipgp** [IPGP/webobs#32]
In the node editing form, in the proc parameters section, the channel list keys are sorted as string elements, not numbers. So, if a node has more than 9 channels, the list is disordered and the data used in a plot don't correspond to the plot label, because of the generated configuration containing:

PROC.MYPROC.CHANNEL_LIST|1,10,2,3,6,8,9

Instead of:

PROC.MYPROC.CHANNEL_LIST|1,2,3,6,8,9,10

This line is used in readfmtdata_dsv.m to filter data in the same order.

The attached patch fixes this bug
[bug_formNODE_channel_list.patch.txt](https://github.com/IPGP/webobs/files/3617959/bug_formNODE_channel_list.patch.txt)

**Comment by beaudu** [comment]
Thanks Alexis.
