### ISSUE TITLE
mc3.pl: no location information for automatic events

### ISSUE THREAD

**Issue by XavierBeguin** [IPGP/webobs#37]
I've been made aware of an issue on our _Main Courante_ (log book?): automatic events imported from our SeisComp3 catalogue (with type `AUTOMATIC`) never showed the epicenter information in the `epicenter` column.

This column always displayed "A not locatable" and no location information was shown in the infotip one get when hovering the cursor on the this column.

After digging in the `mc3.pl` script, it seems that the culprit is [line 703](https://github.com/IPGP/webobs/blob/9fec7e1765c2387298487df17be2c8aedb6e0767/CODE/cgi-bin/mc3.pl#L703) introduced 2 months ago (9 Sept.) by d154b416:
```
$QML{type} = "not locatable" if ($QML{type} eq ""); 
```
Automatic events imported from our SeisComP3 catalogue having no `type` field, `$QML{type}` is empty, and the script was considering these events as not locatable and therefore did not show the epicenter.

Simply commenting/removing line 703 seems to correctly fix the issue: the automatic epicenter location is shown again on automatic events. However, there must be a reason why this line was introduced by commit d154b416, so I am concerned that this simple fix could create other issues in the script for other special cases.

François, could you have a look and tell me what would be the consequences of removing line 703? Thanks!

**Comment by XavierBeguin** [comment]
This issue has just been reported to me once again (however, since 1.5 years, nobody else noticed it, so I guess nobody really cares about event locations and it's not urgent).

**Comment by beaudu** [comment]
The line has been commented. To keep the former functionality (i.e., hidding location for empty type events like automatic), just add an empty string in the `SC3_EVENT_TYPES_NOLOCATION` list.
