### ISSUE TITLE
proc  GNSS : add capabilitie to use a 12 month and 6 month sinusoidal correction

### ISSUE THREAD

**Issue by jmsaurel** [IPGP/webobs#48]
The `VECTORS_VELOCITY_REF` option should also support a fixed combination of sinus and cosinus at 6 and 12 month to correct time series with seasonal effect estimated elsewhere

**Comment by beaudu** [comment]
we need details on the model. Please provide exact equations with list of parameters, e.g., phase origin and amplitude for cos/sin, one set of parameters for each component?

**Comment by RaphaelGrandin** [comment]
Here are the formulas that I use:

```python
elif param == 'sinus1':         # 1st periodic component, sinus term
    G1 = np.array([np.sin((a-date_ref_flt)/(365.25*24*3600)*2*np.pi)], dtype=float)
elif param == 'cosinus1':       # 1st periodic component, cosinus term
    G1 = np.array([np.cos((a-date_ref_flt)/(365.25*24*3600)*2*np.pi)], dtype=float)
elif param == 'sinus2':         # 2nd periodic component, sinus term
    G1 = np.array([np.sin((a-date_ref_flt)*2/(365.25*24*3600)*2*np.pi)], dtype=float)
elif param == 'cosinus2':       # 2nd periodic component, cosinus term
    G1 = np.array([np.cos((a-date_ref_flt)*2/(365.25*24*3600)*2*np.pi)], dtype=float)
```
The user could provide the value of the factor to be multiplied by each of these components.

Unit of `a` is seconds. `date_ref_flt` is set to 2014/1/1 by default (in seconds, too). So `a-date_ref_flt` is seconds since 2014/1/1, and `(a-date_ref_flt)/(365.25*24*3600)` is in years since since 2014/1/1.

Here are a set of test values that I have estimated for the Mayotte dataset (all units are millimeters):
| |  East | North  | Up  | 
|---|---|---|---|
| sinus1 |  -0.5214	   |  0.6970 |  -0.4322 | 
| cosinus1 |  0.2408 |  1.3246 | 0.8702  | 
| sinus2 | -0.1320  | -0.2225  | -0.7915  |
| cosinus2 |  -0.4028  | 0.6172  |  -1.6931 | 

Below, you'll find the daily predicted East, North, Up displacements:
[Atmo_GPS_Mayotte_ENU.txt](https://github.com/IPGP/webobs/files/4487624/Atmo_GPS_Mayotte_ENU.txt)

Peak-to-peak amplitude is 1.5 mm, 4.5 mm and 5 mm, respectively, for East, North and Up displacements.

**Comment by jmsaurel** [comment]
Raphaël,

So `sinus1/cosinus1` is 12 month and `sinus2/cosinus2` is 6 month, right ?

Regarding the days, are you refering to midnight ?
Or midday  ?

I guess midday, like GNSS results ?

WebObs code can handle GNSS data at various sampling rate, not only daily measurements, but potentially hour measurement or so on.
So we need to be a little more precise regarding the time reference phase, even for daily values.

**Comment by RaphaelGrandin** [comment]
Yes, this is correct: 12 months and 6 months.

For the `a` array, which contains the GPS times, I have the following for the first and last record:

```python
# First record a[0] :
1553208900                       #  Unix timestamp
2019-03-21 23:55:00
# Last record a[-1] :
1586991300                       #  Unix timestamp
2020-04-16 00:55:00
```

As for the reference date, `date_ref_flt `, here's what I have:
```python
# date_ref_flt :
1388530800                      #  Unix timestamp
2014-01-01 00:00:00
```

**Comment by jmsaurel** [comment]
Ok, so reference is midnight.

By the way, it looks strange that the GPS records are not at a the same hour everyday.

General equations would be.

`A * sin(2*pi*(t-T_0)/1year)`
`B * cos(2*pi*(t-T_0)/1year)`
`C * sin(2*pi*(t-T_0)/6month)`
`D * cos(2*pi*(t-T_0)/6month)`

And 13 parameters :
* A-e, A-n, A-z
* B-e, B-n, B-z
* C-e, C-n, C-z
*  D-e, D-n, D-z
* T_0

Some more questions : 
* same set of parameters for all stations ?
* same T_0 for 6 month and 1 year ?

**Comment by RaphaelGrandin** [comment]
> same set of parameters for all stations ?

Yes, for now.

> same T_0 for 6 month and 1 year ?

Yes.

> By the way, it looks strange that the GPS records are not at a the same hour everyday.

Uneven temporal samplig comes from the WebObs outputs in the files MADCXXX_all.txt. I just propagated the precise time that was displayed in these files.

**Comment by RaphaelGrandin** [comment]
## 1st March 2022 Update

#### Here is the predicted displacement estimated from GRACE, using the method of [Chanard et al. (2018)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017JB015245).

The following file contains the predicted displacement sampled regularly in time, resulting from a fit of the stacked GRACE-predicted displacements at MAYG:
[GRACE_fit_harmonic_order2_V20220301_RG.txt](https://github.com/IPGP/webobs/files/8163827/GRACE_fit_harmonic_order2_V20220301_RG.txt)

This time-series is generated using the following Python function:
```python
def curve2(x, a0, a1, b1, a2, b2):
    return a0 + a1*np.cos(x*2*np.pi) + b1*np.sin(x*2*np.pi) + a2*np.cos(x*2.*2*np.pi) + b2*np.sin(x*2.*2*np.pi)
```

... where x is the time (in fractional years, first column of the ASCII file), and using the following parameters for a0, a1, b1, a2 and b2, respectively (*beware: there has been a change of convention w.r.t. previous table*):
Param | East | North | Up
-- |-- | -- | --
a0 (constant) | 0.00191131 | -0.06574762 | 0.3547631
a1 (cosinus1) | 0.14967226 | 0.81123238 | 1.9536142
b1 (sinus1) | -0.89186411 | 0.46011307 | -0.19187458
a2 (cosinus2) | 0.04106301 | 0.10315703 | 0.12726141
b2 (sinus2) | 0.06356012 | -0.26497679 | -0.28501726



Parameters in the table are estimated by fitting the stacked GRACE-predicted displacement.

### Reference

Chanard, K., Fleitout, L., Calais, E., Rebischung, P., & Avouac, J. P. (2018). Toward a global horizontal and vertical elastic load deformation model derived from GRACE and GNSS station position time series. Journal of Geophysical Research: Solid Earth, 123(4), 3225-3237.

**Comment by jmsaurel** [comment]
Solved by commit https://github.com/IPGP/webobs/commit/2764a9bcb6833d462fcf12316d93fada446e92db
