### ISSUE TITLE
Allow several pictures per event in the Main Courante

### ISSUE THREAD

**Issue by claudiodsf** [IPGP/webobs#51]
@jmsaurel and I interfaced to WebObs an automated event detector for Very Long Period events (Mayotte), which generates custom images (in the `Sefran` column) showing the detection with spectrograms and other useful parameters (@jmsaurel can explain the technical details).

This automated detection can be then validated by a user, but the validation has the effect to replace the custom image with an image taken from Sefran, where the detected events are more difficult to see.

It would be nice to be able to keep both the images and have some arrow icon in the image view to switch between the two.

Hope it's clear 😉

**Comment by jmsaurel** [comment]
The code filling in new lines in the MainCourante copies the image file in the MainCourante image directory and place the name in the MainCourante line.

This image is replaced whenever editing the MainCourante.

A trick could be to have a directory instead an image for some events (to maintain backward compatibility).
* If the image field in the MainCourante contain an extension, retain actual behaviour
* If the image field in the MainCourante doesn't contain an extension, then it's a directory and all images inside it should be visible.
The sefran3.pl form would place new (or updated) SefraN3 image inside this directory too.

**Comment by XavierBeguin** [comment]
Hi Claudio, Hi Jean-Marie,

I was precisely doing some future cleanup in `mc3.pl`, so I took some time to implement your request.

However, I chose not to use a directory to store the multiple images but to allow a comma separated list of image filenames to be provided in the 'Sefran' colum of the MC3 entry. I think this is easier to manage and introduces fewer changes both in the code and on the storage side. You're welcome to try and convince me that using a directory is actually better if you had any reason to request this particular implementation.

Please try the changes proposed in 61635a9 (use `git fetch` and `git checkout feature-mc3-multiple-event-images-51` to fetch the changes, or simply download the raw modified files [mc3.pl](https://github.com/IPGP/webobs/blob/feature-mc3-multiple-event-images-51/CODE/cgi-bin/mc3.pl) and [wolb.js](https://raw.githubusercontent.com/IPGP/webobs/feature-mc3-multiple-event-images-51/CODE/js/wolb.js)).

Let me know if this works for you. I think we should further refine fonctional requests here if needed, but technical implementation should be discussed in #53. Thanks.

**Comment by jmsaurel** [comment]
Hello @XavierBeguin ,

Change tried and it works for display, thanks.

Now should change to have it work on edition too.

**Comment by jmsaurel** [comment]
Since commit a0b5d8177a4af56ca47807b0819401d4ddc9eef5, I think we can close this issue

**Comment by XavierBeguin** [comment]
Granted, I should have assigned myself to the PR to make it totally clear I intended to keep working on it, and I should have dropped a word stating that I was going to have a look at your contributions and remarks on #53 (I was not expecting my other priorities to take me so long).

But you did double work by submitting code I was already working on and merged my PR before I had the time to look at your contributions and address your remarks. If this issue was urgent, the good way to go would have been to notify me of this urgency to give me a chance to reorganise my priorities.

I'm sorry but this is bad collaborative work IMO.
