### ISSUE TITLE
Suggestion: use GitHub project boards instead of Wiki for tracking TOFIX and TODO lists.

### ISSUE THREAD

**Issue by claudiodsf** [IPGP/webobs#6]
Normally a GitHub Wiki is a place to host documentation (https://help.github.com/articles/about-wikis/)

Project Boards (https://help.github.com/articles/about-project-boards/) seem more appropriate for task management.

**Comment by beaudu** [comment]
todo and tofix lists have been removed from the wiki page. Instead, there is a link to the documentation as suggested.
