### ISSUE TITLE
No auto-closing tab and sefran auto-refresh anymore when adding a new event 

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#61]
Greetings all,
I am reporting an issue concerning the sefran which appeared about 1 week ago. Jean-Marie and Patrice worked on the Mayotte sefran config file at the time but this does not seem to be linked. 

So here is the bug.
When we add a new event, the processing tab does not close itself, so we remain "stuck" on it. The tab displays "Editing Main Courante Sismicité...".
So we have to close it manually and then reload the sefran page to see our event.
Deleting the event does not provoke the error.

This problem only appears on recent web broswers, here is a list :
Bug : 
- W10 + FF 79.0
- Lubuntu 18.04 + Firefox 79.0
- OSX Mojave + Firefox 79.0
- OSX Mojave + Safari 13.1.2
- OSX High Sierra + FF 79.0
- Ubuntu 18.04.4+ FF 79.0

No bug :
- Lubuntu 18.04 + Firefox 75.0
- OSX Mojave + Opera 70.0
- W10 + Microsoft Edge 84.0.522.52  (I know this is evil, but that was only for a quick test J )

Our webobs version is 2.1.5a.

Thanks a lot in advance for your help !
Cyp

**Comment by XavierBeguin** [comment]
Hi Cyprien,
Please check that e97f312 indeed fixes this issue. I could replicate it on Firefox 79 and this fix seems to resolve the problem while still being compatible with Firefox 68.11 ESR. It has however only been tested on Linux with these two versions of Firefox.

**Comment by beaudu** [comment]
Thanks very much Xavier for this fix. It will help a lot the OVPF staff!

**Comment by cyprien-griot** [comment]
Thanks a lot ! It works fine on W10 as well. We're all happy here J

**Comment by XavierBeguin** [comment]
You're welcome. Good to see it works fine.
