### ISSUE TITLE
Proc parameters associated to a node disappear after node modifcation

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#67]
Greetings all,

I am reporting an issue we have just found  in WebObs : changing a field in a node's configuration (for instance deleting or adding a new feature, modifying the description, etc.) causes the disappearance of that node's proc parameters (FID, network, acq, channel, etc.).

Is there a way we do not know to avoid this ? Or is this really a bug ?

Thanks a lot in advance for your help.

Regards,
Cyprien

**Comment by beaudu** [comment]
Hi Cyprien,
Can you indicate the release version that you are using?
François

**Comment by cyprien-griot** [comment]
We are using WebObs-2.1.5a

**Comment by beaudu** [comment]
I was able to reproduce the issue: it happens when editing a node from an associated VIEW. The problem did not happen when the node is edited through a PROC. If you are able to test the new scrip formNODE.pl, and tell me if it solves your case(s).

**Comment by cyprien-griot** [comment]
Hi François,

Sorry for the delay, I didn't have the time to try the fix earlier.
Everything is now working well, thank you a lot ! :) And sorry for the rough explication I gave when I tried to explain the issue..

@+
