### ISSUE TITLE
Graph title formatting issue when node alias or name contains an underscore

### ISSUE THREAD

**Issue by XavierBeguin** [IPGP/webobs#7]
Graph titles being formatted using LaTeX, if the node alias (or its name, for that matter) contains a `_` character, the next character will be subscripted. 

A simple solution to this issue would probably be to escape underscores (replacing `_` by `\_`) before setting the title. This solution works for `genplot`:
```diff
--- genplot.m.orig      2019-02-13 09:18:25.210769359 +0800
+++ genplot.m   2019-02-13 09:15:42.883151562 +0800
@@ -147,7 +147,7 @@
                tlabel(tlim,P.GTABLE(r).TZ)

                % title, status and additional information
-               P.GTABLE(r).GTITLE = varsub(pernode_title,V);
+               P.GTABLE(r).GTITLE = strrep(varsub(pernode_title,V), '_', '\_');
                P.GTABLE(r).GSTATUS = [tlim(2),D(n).G(r).last,D(n).G(r).samp];
                P.GTABLE(r).INFOS = {''};
                if ~isempty(k)
```
This should be applied to all procs that generate graphs, as this is done before the call to `mkgraph`. Alternatively, this could be even better to centralise all title formatting using `gtitle.m`? I don't know if `gtitle` is really fitted for this, though.

Below is an illustration of the problem (graph generated by `genplot`; above is the graph title without the proposed correction in the code, below with the correction):

![this screenshot](https://framapic.org/czJQMGQdVEa2/lLk2tGWlOPuJ)

**Comment by XavierBeguin** [comment]
I had to make additional substitutions for also correct the summary graph titles, as well as the summary graph labels displaying the node aliases. Here is the updated diff:
```diff
--- genplot.m.orig      2019-02-13 09:18:25.210769359 +0800
+++ genplot.m   2019-02-13 11:16:49.854115715 +0800
@@ -147,7 +147,7 @@
                tlabel(tlim,P.GTABLE(r).TZ)

                % title, status and additional information
-               P.GTABLE(r).GTITLE = varsub(pernode_title,V);
+               P.GTABLE(r).GTITLE = strrep(varsub(pernode_title,V), '_', '\_');
                P.GTABLE(r).GSTATUS = [tlim(2),D(n).G(r).last,D(n).G(r).samp];
                P.GTABLE(r).INFOS = {''};
                if ~isempty(k)
@@ -191,7 +191,7 @@
                if any(isnan(tlim))
                        tlim = minmax(cat(1,D.tfirstlast));
                end
-               P.GTABLE(r).GTITLE = varsub(summary_title,V);
+               P.GTABLE(r).GTITLE = strrep(varsub(summary_title,V), '_', '\_');
                P.GTABLE(r).GSTATUS = [tlim(2),rmean(cat(1,G.last)),rmean(cat(1,G.samp))];
                P.GTABLE(r).INFOS = {''};

@@ -225,7 +225,7 @@
                                        col = scolor(n);
                                        timeplot(tk,dk,samp,summary_linestyle,'LineWidth',P.GTABLE(r).LINEWIDTH, ...
                                                'MarkerSize',P.GTABLE(r).MARKERSIZE,'Color',col,'MarkerFaceColor',col)
-                                       aliases = cat(2,aliases,{N(n).ALIAS});
+                                       aliases = cat(2,aliases,{strrep(N(n).ALIAS, '_', '\_')});
                                        ncolors = cat(2,ncolors,n);
                                end
                        end
```

**Comment by beaudu** [comment]
forcing underscore normal display in graph titles is a good idea. It can be done in `mkgraph.m` to be applied to all graphs, without the need to change every `superprocs/*.m` functions.

`gtitle.m` is an old function that will be removed in future versions, replaced by the possibility to set any graph titles in the proc's configuration, using local variables, like :
```sh
PERNODE_TITLE|{\fontsize{14}{\bf$node_alias: $node_name} ($timescale)}
SUMMARY_TITLE|{\fontsize{14}{\bf${NAME}} ($timescale)}
```
Presently it has been coded in genplot, gnss, tilt, rsam and sara.

**Comment by XavierBeguin** [comment]
Okey, thanks for your opinion and the information concerning `gtitle`.

Good idea to do the substitution in `mkgraph`. It works for the title:
```diff
--- mkgraph.m.orig      2019-02-13 14:23:41.509673422 +0800
+++ mkgraph.m   2019-02-13 14:22:39.773809514 +0800
@@ -68,7 +68,7 @@

        if isfield(G,'GSTATUS')
                if G.STATUS & length(G.GSTATUS) > 2 & all(~isnan(G.GSTATUS(2:3)))
-                       G.GTITLE = [G.GTITLE, ...
+                       G.GTITLE = [strrep(G.GTITLE, '_', '\_'), ...
                           {sprintf('%s %+02d - Status %03d %% - Sampling %03d %% ',datestr(G.GSTATUS(1)),G.TZ,round(G.GSTATUS(2:3)))}];
                end
        end
@@ -84,7 +84,7 @@
        else
                uid = '';
        end
-       ss = [G.GTITLE,{sprintf('%s\\copyright %s, %s%s',uid,G.COPYRIGHT,datestr(now,'yyyy'),cpr2)}];
+       ss = [strrep(G.GTITLE, '_', '\_'),{sprintf('%s\\copyright %s, %s%s',uid,G.COPYRIGHT,datestr(now,'yyyy'),cpr2)}];
        text(.5,1,regexprep(ss,'\(\)',''),'HorizontalAlignment','center','VerticalAlignment','top','FontSize',8);

        % --- footer
```

 However, I still had to do a substitution in `genplot.m` to correct the node/station alias in the axis label. As the label is added directly to the graph using `text()`, I don't think there is a way to do it in `mkgraph.m`.
Here's the change still necessary in `genplot.m`:
```diff
--- superprocs/genplot.m.orig   2019-02-13 09:18:25.210769359 +0800
+++ superprocs/genplot.m        2019-02-13 14:37:56.439975910 +0800
@@ -225,7 +225,7 @@
                                        col = scolor(n);
                                        timeplot(tk,dk,samp,summary_linestyle,'LineWidth',P.GTABLE(r).LINEWIDTH, ...
                                                'MarkerSize',P.GTABLE(r).MARKERSIZE,'Color',col,'MarkerFaceColor',col)
-                                       aliases = cat(2,aliases,{N(n).ALIAS});
+                                       aliases = cat(2,aliases,{strrep(N(n).ALIAS, '_', '\_')});
                                        ncolors = cat(2,ncolors,n);
                                end
                        end
```

Should I do a pull request for these changes?

**Comment by beaudu** [comment]
- first substitution seems not necessary in `mkgraph.m` (the second will take G.GTITLE before it is displayed);
- for the alias this may occur in many superprocs, not only the `genplot`. So we must find a better generic fix. There is a way to do it in `mkgraph` : it is possible to check all strings in existing text objects using `findobj('type','text')`, and make the substitution on the content. By the way, it will work also for the title ;-)

**Comment by beaudu** [comment]
an other strategy is to escape any underscores in node alias at the node reading level, e.g. `readnode.m`. The advantage is to keep the possibility of using subscripts in graphic titles.
Probably the best solution to solve this issue, finally.

**Comment by XavierBeguin** [comment]
I see what you mean. But I guess there could be cases where you'd want to get the alias using `readnode` for a different purpose than graph display, so you would want to keep the underscore as is at this stage.

In the end I would say it would probably be best to replace underscores in the graph text as you suggested earlier, as it's the place where this should be corrected for display.

I tried a few things to make the substitution using `findobj`, but not all `text` objects are found, and the station alias is only replaced in the first plot of the summary fields (the three others in the graph are left untouched, which is strange). Here's what I tried to add in `mkgraph.m` (there's certainly better ways to write this):
```matlab
    % --- Escape underscores in text, as they would be interpreted in LaTeX.
    all_text = findobj('Type', 'text');
    for i = length(all_text)
        set(all_text(i), 'String', strrep(get(all_text(i), 'String'), '_', '\_'));
    end
```
I don't have time to dig any further, so I'll have to stay with my previous hack for now.

**Comment by beaudu** [comment]
`ALIAS` has only a display purpose, it should be used only for that. Functional node's codes are `FID` and `FID_*`.

Problem of the findobj solution is to replace any subscribe text in the graph. This might happen for geochemical procs, for example.

**Comment by XavierBeguin** [comment]
Good points. In that case, I guess the `readnode` solution is probably
indeed the best after all :)
________________________________
CONFIDENTIALITY: This email is intended solely for the person(s) named and may be confidential and/or privileged. If you are not the intended recipient, please delete it, notify us and do not copy, use, or disclose its contents.
Towards a sustainable earth: Print only when necessary. Thank you.

**Comment by beaudu** [comment]
new `readnode.m` committed that fixes the problem.

**Comment by XavierBeguin** [comment]
Sorry, I have to reopen this issue.

I applied your changes in `readnode.m` and recompiled. Node alias in axis title of the summary graph is fine, but I unfortunately still get a problem with the title on the per node graph:

NODE_ALIAS below is really `MAYON_EVCOUNT`:
![](https://framapic.org/7nSLuFfWbThD/Spkk2iavoBGg)

I haven't looked at the whole code thoroughly, but could it be due to the fact that PERNODE_TITLE is defined using `$node_alias` in its definition, and `varsub` directly reads the `NODE_ALIAS` from the node configuration without using `readnode`?
`PERNODE_TITLE|{\fontsize{14}{\bf$node_alias: $node_name} ($timescale)}`

**Comment by beaudu** [comment]
just commit a change in `varsub.m`. This function uses regex and the escape character was simply lost...
`readnode.m` is used by `readnodes.m` which is used by `readproc.m` so structure `N.ALIAS` is ok everywhere in all the procs.

**Comment by XavierBeguin** [comment]
Thanks! However, it sounds like the escaping was a bit violent. The proc does not really start any more, as underscores in the config file name seem also to have been escaped. Here's the error I get:
```
Error using readcfg (line 75)
config file /opt/webobs/CONF/PROCS/MAYON\_EVCOUNT\_PLOT/MAYON\_EVCOUNT\_PLOT.conf does not exist.
Error in readproc (line 43)
Error in genplot (line 65)
```
Tricky story!

**Comment by beaudu** [comment]
ok, you have underscores in the proc's short name (you like very much underscores right ? ;-) )... new situation for me, but need to be managed also.

**Comment by beaudu** [comment]
new try... but had to edit most of the superproc codes also...

**Comment by beaudu** [comment]
not a good solution, we loose all accents in graph titles... :-/

**Comment by beaudu** [comment]
seems a better fix modifying `varsub.m` again, but just avoiding regex removes the escaped underscores. Advantage is that TeX subscribes are still possible in graph titles if wanted.

**Comment by beaudu** [comment]
<img width="793" alt="capture d ecran 2019-02-16 a 16 14 40" src="https://user-images.githubusercontent.com/16031598/52897396-7bd10800-3206-11e9-8d95-3fe76c838b1c.png">

**Comment by XavierBeguin** [comment]
This solution seems to work fine for me too. Thanks!
