### ISSUE TITLE
validity checkbox in job edit not compatible with Safari

### ISSUE THREAD

**Issue by beaudu** [IPGP/webobs#70]
The new feature introduced in v2.1.6 (checkbox instead of text content) for the validity parameter of scheduler job does not work with Safari 14.0. Note as it works properly with Firefox 81.0.1  and Opera 71.0.3770.228.

**Comment by XavierBeguin** [comment]
I've just had the opportunity to try the job validity checkbox, as well as checkboxes on the user manager page on a Mac with Safari 13.1, and it all worked smoothly.

You will have to tell me what doesn't work for you. Also, make sure you correctly cleared the browser cache, as mentioned in the release notes. Thanks.

**Comment by beaudu** [comment]
To answer your request: I wanted to edit a valid/active job but it opened with a validity box unchecked. After check manually and send the form, the job was disactivated... The behavior was reproductible for other jobs.
But cleaning the browser cache solved all the problems. Thanks very much.
