### ISSUE TITLE
Better choice of spectrogram hotkeys ? 

### ISSUE THREAD

**Issue by claudiodsf** [IPGP/webobs#72]
I like a lot the new spectrogram SEFRAN tool, but I find that `t` / `shift+t` for changing transparency is not really ergonomic.

I would suggest to use to nearby keys like `s` to decrease transparency and `t` to increase it.

**Comment by beaudu** [comment]
Thanks Claudio. OK but the S key is used to toggle the display. What about R and T to decrease and increase transparency?

**Comment by claudiodsf** [comment]
Sorry, I meant `r` and `t` !

**Comment by beaudu** [comment]
done.
