### ISSUE TITLE
Bugs in Search Node Events page

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#79]
Greetings all,

I am reporting 2 bugs with the search node events function (but there are probably others) : 
- searching only one letter displays wrong results. Example : searching letter "a" in "node alias" displays both nodes with and without this letter. I am not sure but I have the feeling it checks both node alias and node name parameters (despite the fact we only see "node alias" on the search page).

- searching something in "grid name" does not work

Thank you a lot in advance.
Regards,
Cyprien

**Comment by cmbapt** [comment]
Hi @cyprien-griot,
Your feeling was good ! The search is doing on node's alias and name. I precised it in the search page. 
I also fixed the search by grid name bug.
Regards 
Baptiste
