### ISSUE TITLE
wdir.pl adds double slash for files located in subbdirectory

### ISSUE THREAD

**Issue by beaudu** [IPGP/webobs#81]
`wdir.pl` adds a double slash in file path when it is located in a subdirectory. It works normally excepted that authorization must use also a double slash. Example:
- page is `WIKI/Subdir/webpage`
- wdir.pl points to `cgi-bin/wpage.pl?file=WIKI/Subdir//Webpage&css=wpage.css`
- authorization must be `WIKI/Subdir//Webpage`

**Comment by cmbapt** [comment]
Hi @beaudu , 
I resolved it in commit [b3d99cb](https://github.com/IPGP/webobs/commit/b3d99cb4e86f3794463d6ff723dd50014222db92), and an other little error in wdir.js.
See you later 
Baptiste
