### ISSUE TITLE
Adding a description field for WebObs users

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#84]
Greetings all,

Would it possible to add a description field for the WebObs users which would be displayed in the Admin Users menu ? This would help a lot to have more information about users, to know where the come from, how much time they'd need the access, or if we have to keep them in database for history, other webobs features, etc.

Thanks a lot in advance !
Cheers

**Comment by beaudu** [comment]
This is a good idea and easily feasible. Adding a field and upgrade existing database is already done for previous updates with a simple sql file used by `setup`. We may also use the **VALIDITY** field (which is a text field) to store a possible access end date. I'll look that for the next release.

**Comment by cyprien-griot** [comment]
Awesome ! I'm looking forward for that next release :)
Thanks
