### ISSUE TITLE
Changing the authors order when creating a new event

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#85]
Greetings all,
Another idea which may be linked to my other request concerning WebObs users (adding a description field). 

In our webobs we have so many users and it is quite unconvenient, when creating a new event, to find the needed users. Especially because they do not appear in alphabetical order..

So a first idea would be at least to have the list in the alphabetical order. 
But would it be possible to create the list with two requests (or another way I may not know), one to display in first the most likely users who interviene on stations (the technical team, so maybe based on the description field ?) and then all the other users in alphabetical order ?

Thanks a lot in advance.
Cheers !

**Comment by beaudu** [comment]
I think this feature already exists: you must configure in **WEBOBS.rc** the variable **EVENTS_ACTIVE_GID** with a group name or a list of coma separated group names. Example:
`EVENTS_ACTIVE_GID|+ADMIN,+DUTY`
to have all the users in groups ADMIN and DUTY appearing at the top of the list when creating/modifying an event.

**Comment by beaudu** [comment]
Actually I just found the issue origin: in the event form, users are sorted but on the user's login, not the name nor UID. The weird consequence is that all logins starting with an uppercase letter are located in the front list, and logins are sometimes very different than name... I consider this as an issue (that will be quickly resolved).
