### ISSUE TITLE
No variable substitution in RAWDATA node configuration

### ISSUE THREAD

**Issue by XavierBeguin** [IPGP/webobs#9]
When defining the `RAWDATA` field in the proc's configuration, variable substitution like `$WEBOBS{ROOT_DATA}` will work fine:
`RAWDATA|$WEBOBS{ROOT_DATA}/DB/TEST_EVCOUNT.dat`

However, using the same value in the node configuration won't work, and no data will be found. Using this kind of definition instead will work:
`PROC.TEST_PLOT.RAWDATA|/opt/webobs/DATA/DB/TEST_EVCOUNT.dat`

I guess there is a missing variable substitution somewhere when reading values from the node configuration file.

**Comment by beaudu** [comment]
thanks Xavier, this is an issue that was identified in my TOFIX list a long time ago ! I will look at it asap.

**Comment by XavierBeguin** [comment]
Ok, cool. I just wanted to make sure it was indeed identified.  One can easily work around this issue, but it is still annoying as I don't want to use hard-coded path anywhere (as using such a path once would defeat the while purpose of using variables). Thanks!

**Comment by beaudu** [comment]
no pb. It is also a good practice to open all identified issues on this github, as suggested by Claudio, instead of using the Wiki and simple tofix list.

**Comment by XavierBeguin** [comment]
I totally agree, as it also helps other users that could face the same issue and avoid duplicate reports.

**Comment by beaudu** [comment]
change in `readcfg.m` to manage node's configuration substructures (parameters associated with a proc). Seems to solve the issue.

**Comment by XavierBeguin** [comment]
This works great, thanks for this quick update!

I took the liberty to directly update the master branch to remove forgotten debugging output in `readcfg.m` to avoid useless lines in the logs.
