### ISSUE TITLE
Adding a date format check in event creation

### ISSUE THREAD

**Issue by cyprien-griot** [IPGP/webobs#93]
Greetings all,

We noticed a little thing which causes an error. When adding (or editing) a new event on a node, if there is no check performed on the date format entered. We can put letters and other special characters. 

For example a user made a mistake and used a ";" instead of ":", which made the event impossible to open again.

Would it be possible to do something to prevent this in the future ? 

Thanks in advance.
Regards,
Cyprien

**Comment by cmbapt** [comment]
Hi @cyprien-griot, 
Your are right, there was a check on the date format but not on time. It's corrected. 
Regards 
Baptiste
